name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer | node
      - name: Install dependencies
        run: pnpm install

      - name: Build step
        run: pnpm build

  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer | node
      - name: Install dependencies
        run: pnpm install

      - name: Lint step
        run: pnpm lint
      - name: Format step
        run: pnpm dlx prettier --check "**/*.{js,ts}"
