name: Main Branch Trigger

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup project
        uses: ./.github/custom-actions/setup-project/action.yml
      - name: Build step
        run: pnpm build

  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Setup project
        uses: ./.github/custom-actions/setup-project/action.yml
      - name: Lint step
        run: pnpm lint
      - name: Format step
        run: pnpm dlx prettier --check "**/*.{js,ts}"
